version: "3"
services:
    app:
        image: golang:1.13
        working_dir: /work
        tty: true
        ports:
            - 8000:8000
        volumes:
            - ./:/work
        environment:
            PORT: 8000
