version: "3"
services:
    app:
        build: .
        working_dir: /work
        tty: true
        ports:
            - 8000:8000
        volumes:
            - ./:/work
        environment:
            - PORT=8000
